"""The one README figure: why ties appear on synthetic graphs and not on real ones.

Regenerated by scripts/update_readme.py; not usually called directly.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from .analyze import load, tie_sets  # noqa: E402

SYNTH = "#4C72B0"
REAL = "#C44E52"
SOLVER_ORDER = ["greedy", "ilp", "dp", "dp_sliding_hirschberg"]


def fig_heterogeneity_vs_ties(g_s, r_s, g_r, r_r, path: Path) -> None:
    """The central figure: uniform items produce ties, heterogeneous ones don't."""
    rows = []
    for graphs, results, kind, colour in (
        (g_s, r_s, "synthetic", SYNTH),
        (g_r, r_r, "real", REAL),
    ):
        ties = {r["label"]: r for r in tie_sets(results)["rows"]}
        per_label: dict[str, list] = {}
        for r in tie_sets(results)["rows"]:
            per_label.setdefault(r["label"], []).append(r)
        for g in graphs:
            cells = per_label.get(g["label"], [])
            if not cells:
                continue
            pairs = len(set(zip(g["memories"], g["runtimes"])))
            frac = sum(c["all_tied"] for c in cells) / len(cells) * 100
            rows.append((g["label"].split("#")[0], pairs, frac, colour, kind))

    fig, ax = plt.subplots(figsize=(7, 4.4))
    seen = set()
    # stagger labels where points coincide
    used: dict[tuple[int, int], int] = {}
    for name, pairs, frac, colour, kind in sorted(rows, key=lambda r: (r[1], r[0])):
        ax.scatter(pairs, frac, s=110, color=colour, zorder=3,
                   label=kind if kind not in seen else None)
        seen.add(kind)
        slot = used.get((pairs, round(frac)), 0)
        used[(pairs, round(frac))] = slot + 1
        ax.annotate(name, (pairs, frac), textcoords="offset points",
                    xytext=(9, 6 - slot * 13), fontsize=8)
    ax.set_xlabel("distinct (memory, runtime) pairs among items")
    ax.set_ylabel("cells where all 4 solvers tie (%)")
    ax.set_title("Solver ties are a symptom of uniform items, not of the objective")
    ax.set_ylim(-6, 106)
    ax.grid(alpha=0.25, zorder=0)
    ax.legend(fontsize=9)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def make_figure(synthetic_dir: str | Path = "out",
                real_dir: str | Path = "out_hf",
                figdir: str | Path = "docs/figures") -> Path:
    g_s, r_s = load(synthetic_dir)
    g_r, r_r = load(real_dir)
    figdir = Path(figdir)
    figdir.mkdir(parents=True, exist_ok=True)
    path = figdir / "heterogeneity_vs_ties.png"
    fig_heterogeneity_vs_ties(g_s, r_s, g_r, r_r, path)
    return path
