"""Regenerate the README's results section and figure from the raw output dirs.

The README should never be edited by hand between the RESULTS markers. Run this
after any sweep so the published numbers and the committed figure cannot drift
apart from what is in out/ and out_hf/.

    python scripts/update_readme.py
"""

from __future__ import annotations

import argparse
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ackaudit.analyze import heterogeneity, load, q1_input_scale, tie_sets  # noqa: E402
from ackaudit.figures import make_figure  # noqa: E402

START = "<!-- RESULTS:START -->"
END = "<!-- RESULTS:END -->"


def _errs(results):
    return [
        (r["true_peak_memory"] - r["proxy_peak_memory"]) / r["proxy_peak_memory"] * 100
        for r in results
        if r["ok"] and r["proxy_peak_memory"] > 0
    ]


def _summary(graphs, results):
    errs = _errs(results)
    ties = tie_sets(results)
    q1 = q1_input_scale(graphs)
    return {
        "n_graphs": len(graphs),
        "n_min": q1.get("n_items_min", 0),
        "n_max": q1.get("n_items_max", 0),
        "measurements": len(errs),
        "median": statistics.median(errs) if errs else float("nan"),
        "exact_pct": sum(e <= 1e-9 for e in errs) / len(errs) * 100 if errs else 0.0,
        "over10": sum(e > 10 for e in errs) / len(errs) * 100 if errs else 0.0,
        "all_tied": ties["frac_all_tied"] * 100 if ties["n_cells"] else 0.0,
        "med_spread": ties["median_tied_spread_pct"],
        "max_spread": ties["max_tied_spread_pct"],
        "dp_table_mb": q1.get("dp_table_mb_max", 0.0),
        "W_max": q1.get("W_max", 0),
    }


def _solver_medians(results):
    by: dict[str, list[float]] = {}
    for r in results:
        if r["ok"]:
            by.setdefault(r["solver"], []).append(r["solver_seconds"] * 1000)
    return {k: statistics.median(v) for k, v in by.items()}


def build_section(synth_dir: str, real_dir: str, schedule: str, torch_version: str) -> str:
    g_s, r_s = load(synth_dir)
    g_r, r_r = load(real_dir)
    s, r = _summary(g_s, r_s), _summary(g_r, r_r)
    med_r = _solver_medians(r_r)

    lines = [
        START,
        "",
        f"torch {torch_version}, CPU, `schedule={schedule}`, `PYTHONHASHSEED=0`.",
        "Generated by `scripts/update_readme.py`; do not edit between the markers.",
        "",
        "|  | synthetic | llama + bert |",
        "|---|---|---|",
        f"| graphs | {s['n_graphs']} | {r['n_graphs']} |",
        f"| n items | {s['n_min']} to {s['n_max']} | {r['n_min']} to {r['n_max']} |",
        f"| measurements | {s['measurements']} | {r['measurements']} |",
        f"| median proxy error | {s['median']:+.1f}% | **{r['median']:+.1f}%** |",
        f"| plans where the objective is exact | {s['exact_pct']:.0f}% | {r['exact_pct']:.0f}% |",
        f"| plans over 10% error | {s['over10']:.0f}% | {r['over10']:.0f}% |",
        f"| **cells where all 4 solvers tie** | **{s['all_tied']:.0f}%** | **{r['all_tied']:.0f}%** |",
        f"| median tied true-peak spread | {s['med_spread']:.1f}% | {r['med_spread']:.1f}% |",
        f"| max tied spread | {s['max_spread']:.1f}% | {r['max_spread']:.1f}% |",
        "",
        "![solver ties versus item heterogeneity](docs/figures/heterogeneity_vs_ties.png)",
        "",
        "**Item heterogeneity is what decides it.** Real models have varied item",
        "sizes and runtimes; the synthetic graphs here do not, by construction.",
        "",
        "| graph | n | distinct mem | distinct rt | distinct pairs |",
        "|---|---|---|---|---|",
    ]
    for h in sorted(heterogeneity(g_s) + heterogeneity(g_r), key=lambda x: x["distinct_pairs"]):
        lines.append(
            f"| `{h['label'].split('#')[0]}` | {h['n_items']} | {h['distinct_memories']} "
            f"| {h['distinct_runtimes']} | {h['distinct_pairs']} |"
        )

    order = ["greedy", "ilp", "dp", "dp_sliding_hirschberg"]
    lines += [
        "",
        "**Input scale and solver cost.** The partitioner clamps `memory_budget` to",
        "`[0, 1]` and the solver hardcodes `S = 10000`, so the quantised capacity `W`",
        f"has a structural ceiling of 10,000. Observed max W = {r['W_max']}, largest",
        f"`dp_knapsack` table {r['dp_table_mb']:.2f} MB. Median solver wall time on",
        "llama + bert:",
        "",
        "| solver | median |",
        "|---|---|",
    ]
    for name in order:
        if name in med_r:
            v = med_r[name]
            lines.append(f"| `{name}` | {v:.2f} ms |" if v < 1 else f"| `{name}` | {v:.1f} ms |")
    lines += ["", END]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--synthetic", default="out")
    ap.add_argument("--real", default="out_hf")
    ap.add_argument("--readme", default="README.md")
    ap.add_argument("--schedule", default="fx_order")
    args = ap.parse_args()

    import torch

    fig = make_figure(args.synthetic, args.real)
    section = build_section(args.synthetic, args.real, args.schedule, torch.__version__)

    p = Path(args.readme)
    text = p.read_text()
    if START not in text or END not in text:
        raise SystemExit(f"{args.readme} is missing the {START} / {END} markers")
    before = text[: text.index(START)]
    after = text[text.index(END) + len(END) :]
    p.write_text(before + section + after)
    print(f"updated {p} and {fig}")


if __name__ == "__main__":
    main()
